stages:
  drop-dup:
    cmd: python3 scripts/data_scripts/drop_dup.py data/raw/diamonds.csv
    deps:
    - data/raw/diamonds.csv
    - scripts/data_scripts/drop_dup.py
    outs:
    - data/stage1/
  drop-na:
    cmd: python3 scripts/data_scripts/drop_na.py data/stage1/diamonds.csv
    deps:
    - data/stage1/diamonds.csv
    - scripts/data_scripts/drop_na.py
    outs:
    - data/stage2/
  drop-outliers:
    cmd: python3 scripts/data_scripts/drop_outliers.py data/stage2/diamonds.csv
    deps:
    - data/stage2/diamonds.csv
    - scripts/data_scripts/drop_outliers.py
    params:
    - drop_outliers.carat.max
    - drop_outliers.carat.min
    - drop_outliers.depth.max
    - drop_outliers.depth.min
    - drop_outliers.price.max
    - drop_outliers.price.min
    - drop_outliers.table.max
    - drop_outliers.table.min
    - drop_outliers.x.min
    - drop_outliers.x.min
    - drop_outliers.y.max
    - drop_outliers.y.max
    - drop_outliers.z.max
    - drop_outliers.z.max
    outs:
    - data/stage3/
  preprocessors:
    cmd: python3 scripts/data_scripts/preprocessors.py data/stage3/diamonds.csv
    deps:
    - data/stage3/diamonds.csv
    - scripts/data_scripts/preprocessors.py
    params:
    - preprocessors.PF_degree
    - preprocessors.PF_interaction
    - preprocessors.scalers
    - preprocessors.target
    outs:
    - data/stage4/
  split:
    cmd: python3 scripts/data_scripts/train_test_split.py data/stage4/diamonds.csv
    deps:
    - data/stage4/diamonds.csv
    - scripts/data_scripts/train_test_split.py
    params:
    - split.seed
    - split.split_ratio
    - split.target
    outs:
    - data/stage5/
  train:
    cmd: python3 scripts/model_scripts/model_knr.py data/stage5/train.csv model_knr
    deps:
    - data/stage5/train.csv
    - scripts/model_scripts/model_knr.py
    params:
    - train.n_neighbors
    - train.target
    - train.weights
    outs:
    - models/
  evaluate:
    cmd: python3 scripts/model_scripts/evaluate.py data/stage5/test.csv models/model_knr.pkl
    deps:
    - data/stage5/test.csv
    - models/model_knr.pkl
    - scripts/model_scripts/evaluate.py
    params:
    - train.n_neighbors
    - train.target
    - train.weights
    metrics:
    - evaluate/scores_extended.json:
        cache: false
