drop_outliers:
  carat: 
    min: 0
    max: 3
  depth:
    min: 55
    max: 70
  table:
    min: 50
    max: 70
  price:
    min: null
    max: null
  x:
    min: 3
    max: 9
  y:
    min: 3
    max: 10
  z:
    min: 2
    max: 6


split:
  split_ratio: 0.3
  seed: 42

train:
  seed: 42
  max_depth: 4
